providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs", "python311", "gcc"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build && pip install -r requirements.txt"]

[start]
cmd = "cd frontend && npm start"
